### ISSUE TITLE
Topic Modeling

### ISSUE THREAD

**Issue by cfoster0** [EleutherAI/pile-explorer#2]

**Comment by cfoster0** [comment]
@StellaAthena and I talked about what plots we want from the topic modeling. The plan is to do LDA on a dataset-by-dataset basis, and to compare their similarities. One option here is to visualize it as a matrix of perplexities (visually, a similarity matrix like [this](https://kapilddatascience.files.wordpress.com/2016/05/san_francisco_sim_matrix_greens_yellow_green_blue.png?w=1117&h=&zoom=2)) for a topic model of one dataset on another.

**Comment by cfoster0** [comment]
Of course, we also want to just show the topic groupings, to give folks a feel for what each dataset contains.

**Comment by StellaAthena** [comment]
I found [this demo](https://radimrehurek.com/gensim/auto_examples/core/run_core_concepts.html) which seems to do pretty much exactly what we want. Worth checking out, especially if you haven’t made a whole lot of progress.
